<a href="https://colab.research.google.com/github/ltoosaint24/DS-Unit-2-Kaggle-Challenge/blob/master/Loveline_Toussaint__LS_DS_223_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 2, Module 3*

---

# Cross-Validation


## Assignment
- [ ] [Review requirements for your portfolio project](https://lambdaschool.github.io/ds/unit2), then submit your dataset.
- [ ] Continue to participate in our Kaggle challenge. 
- [ ] Use scikit-learn for hyperparameter optimization with RandomizedSearchCV.
- [ ] Submit your predictions to our Kaggle competition. (Go to our Kaggle InClass competition webpage. Use the blue **Submit Predictions** button to upload your CSV file. Or you can use the Kaggle API to submit your predictions.)
- [ ] Commit your notebook to your fork of the GitHub repo.


**You can't just copy** from the lesson notebook to this assignment.

- Because the lesson was **regression**, but the assignment is **classification.**
- Because the lesson used [TargetEncoder](https://contrib.scikit-learn.org/categorical-encoding/targetencoder.html), which doesn't work as-is for _multi-class_ classification.

So you will have to adapt the example, which is good real-world practice.

1. Use a model for classification, such as [RandomForestClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html)
2. Use hyperparameters that match the classifier, such as `randomforestclassifier__ ...`
3. Use a metric for classification, such as [`scoring='accuracy'`](https://scikit-learn.org/stable/modules/model_evaluation.html#common-cases-predefined-values)
4. If you’re doing a multi-class classification problem — such as whether a waterpump is functional, functional needs repair, or nonfunctional — then use a categorical encoding that works for multi-class classification, such as [OrdinalEncoder](https://contrib.scikit-learn.org/categorical-encoding/ordinal.html) (not [TargetEncoder](https://contrib.scikit-learn.org/categorical-encoding/targetencoder.html))



## Stretch Goals

### Reading
- Jake VanderPlas, [Python Data Science Handbook, Chapter 5.3](https://jakevdp.github.io/PythonDataScienceHandbook/05.03-hyperparameters-and-model-validation.html), Hyperparameters and Model Validation
- Jake VanderPlas, [Statistics for Hackers](https://speakerdeck.com/jakevdp/statistics-for-hackers?slide=107)
- Ron Zacharski, [A Programmer's Guide to Data Mining, Chapter 5](http://guidetodatamining.com/chapter5/), 10-fold cross validation
- Sebastian Raschka, [A Basic Pipeline and Grid Search Setup](https://github.com/rasbt/python-machine-learning-book/blob/master/code/bonus/svm_iris_pipeline_and_gridsearch.ipynb)
- Peter Worcester, [A Comparison of Grid Search and Randomized Search Using Scikit Learn](https://blog.usejournal.com/a-comparison-of-grid-search-and-randomized-search-using-scikit-learn-29823179bc85)

### Doing
- Add your own stretch goals!
- Try other [categorical encodings](https://contrib.scikit-learn.org/categorical-encoding/). See the previous assignment notebook for details.
- In additon to `RandomizedSearchCV`, scikit-learn has [`GridSearchCV`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html). Another library called scikit-optimize has [`BayesSearchCV`](https://scikit-optimize.github.io/notebooks/sklearn-gridsearchcv-replacement.html). Experiment with these alternatives.
- _[Introduction to Machine Learning with Python](http://shop.oreilly.com/product/0636920030515.do)_ discusses options for "Grid-Searching Which Model To Use" in Chapter 6:

> You can even go further in combining GridSearchCV and Pipeline: it is also possible to search over the actual steps being performed in the pipeline (say whether to use StandardScaler or MinMaxScaler). This leads to an even bigger search space and should be considered carefully. Trying all possible solutions is usually not a viable machine learning strategy. However, here is an example comparing a RandomForestClassifier and an SVC ...

The example is shown in [the accompanying notebook](https://github.com/amueller/introduction_to_ml_with_python/blob/master/06-algorithm-chains-and-pipelines.ipynb), code cells 35-37. Could you apply this concept to your own pipelines?


### BONUS: Stacking!

Here's some code you can use to "stack" multiple submissions, which is another form of ensembling:

```python
import pandas as pd

# Filenames of your submissions you want to ensemble
files = ['submission-01.csv', 'submission-02.csv', 'submission-03.csv']

target = 'status_group'
submissions = (pd.read_csv(file)[[target]] for file in files)
ensemble = pd.concat(submissions, axis='columns')
majority_vote = ensemble.mode(axis='columns')[0]

sample_submission = pd.read_csv('sample_submission.csv')
submission = sample_submission.copy()
submission[target] = majority_vote
submission.to_csv('my-ultimate-ensemble-submission.csv', index=False)
```

In [26]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Kaggle-Challenge/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'

In [27]:
import pandas as pd

# Merge train_features.csv & train_labels.csv
train = pd.merge(pd.read_csv(DATA_PATH+'waterpumps/train_features.csv'), 
                 pd.read_csv(DATA_PATH+'waterpumps/train_labels.csv'))

# Read test_features.csv & sample_submission.csv
test = pd.read_csv(DATA_PATH+'waterpumps/test_features.csv')
sample_submission = pd.read_csv(DATA_PATH+'waterpumps/sample_submission.csv')

In [28]:
train.sample(50)

id  amount_tsh  ... waterpoint_type_group             status_group
30239  23713         0.0  ...    communal standpipe  functional needs repair
57428  42320         0.0  ...                 other               functional
51602  24872         0.0  ...    communal standpipe           non functional
3302   55900       100.0  ...    communal standpipe               functional
6127   24800         0.0  ...    communal standpipe               functional
34458  63273      2000.0  ...             hand pump               functional
58392  34506         0.0  ...    communal standpipe           non functional
47261  17865         0.0  ...    communal standpipe           non functional
51372  53790         0.0  ...    communal standpipe           non functional
49031  34364       200.0  ...             hand pump               functional
58210  53656         0.0  ...             hand pump           non functional
19426  35383         0.0  ...    communal standpipe           non functional
10444  42462         0.0  ...    communal standpipe           non functional
35881  44924         0.0  ...    communal standpipe               functional
23914  61096         0.0  ...             hand pump               functional
42718  63450        50.0  ...    communal standpipe               functional
3517   39345         0.0  ...    communal standpipe           non functional
34643  50664         0.0  ...    communal standpipe  functional needs repair
33274  48386         0.0  ...    communal standpipe  functional needs repair
25232  42606         0.0  ...             hand pump           non functional
55257   6085        10.0  ...    communal standpipe           non functional
6566   12867         0.0  ...    communal standpipe           non functional
42150   8334         0.0  ...                 other           non functional
42553  39078       200.0  ...             hand pump           non functional
30750  48256        20.0  ...             hand pump               functional
2247   10587        50.0  ...    communal standpipe               functional
729    32164       500.0  ...    communal standpipe               functional
32438  19968         0.0  ...             hand pump               functional
43462  71865       300.0  ...             hand pump               functional
18792  20421         0.0  ...    communal standpipe               functional
36229  66868      1000.0  ...             hand pump               functional
13398  71650         0.0  ...    communal standpipe               functional
17854  40473         0.0  ...             hand pump               functional
41410  31885      1000.0  ...    communal standpipe           non functional
2353   54806      1200.0  ...    communal standpipe               functional
49187   4142      2000.0  ...             hand pump               functional
15256   4007         0.0  ...    communal standpipe           non functional
3290   67999         0.0  ...             hand pump               functional
43876   9727         0.0  ...             hand pump               functional
52508  49542       600.0  ...    communal standpipe  functional needs repair
25268  12153         0.0  ...    communal standpipe               functional
32332  58326     12000.0  ...    communal standpipe               functional
25805  11607         0.0  ...             hand pump  functional needs repair
54115  40559         0.0  ...    communal standpipe               functional
46192   3354         0.0  ...             hand pump           non functional
19766  23760         0.0  ...    communal standpipe               functional
29026  24821         0.0  ...    communal standpipe  functional needs repair
21019  35922         0.0  ...                 other           non functional
10841  32601        10.0  ...    communal standpipe               functional
42285  44904        50.0  ...    communal standpipe               functional

[50 rows x 41 columns]

In [29]:
test.sample(50)

id  amount_tsh  ...              waterpoint_type waterpoint_type_group
12329  15606         0.0  ...           communal standpipe    communal standpipe
7489   26066        30.0  ...                        other                 other
10922  60463         0.0  ...           communal standpipe    communal standpipe
5786   31697         0.0  ...           communal standpipe    communal standpipe
4934    6947       200.0  ...                        other                 other
12310  15346      1000.0  ...           communal standpipe    communal standpipe
9243    5557         0.0  ...           communal standpipe    communal standpipe
7471   45263         0.0  ...           communal standpipe    communal standpipe
759    11443         0.0  ...           communal standpipe    communal standpipe
12145  70553         0.0  ...           communal standpipe    communal standpipe
8250   72699         0.0  ...                        other                 other
12111  18437        50.0  ...           communal standpipe    communal standpipe
7687   43087         0.0  ...           communal standpipe    communal standpipe
4612   46075         0.0  ...                        other                 other
8989   70159       500.0  ...                    hand pump             hand pump
12489  38956         0.0  ...           communal standpipe    communal standpipe
1490   27893      1000.0  ...                    hand pump             hand pump
13045  16763       500.0  ...           communal standpipe    communal standpipe
2255   39856        20.0  ...           communal standpipe    communal standpipe
4099   15631         0.0  ...           communal standpipe    communal standpipe
8411   54721      1000.0  ...           communal standpipe    communal standpipe
1561   39554         0.0  ...                    hand pump             hand pump
9830   39021        30.0  ...           communal standpipe    communal standpipe
10193  64037       300.0  ...           communal standpipe    communal standpipe
10721  34734         0.0  ...           communal standpipe    communal standpipe
11782  38468      1000.0  ...  communal standpipe multiple    communal standpipe
1296   19492        30.0  ...           communal standpipe    communal standpipe
12160  47488       600.0  ...           communal standpipe    communal standpipe
10658  11347         0.0  ...           communal standpipe    communal standpipe
12806  35428         0.0  ...  communal standpipe multiple    communal standpipe
7597   20259         0.0  ...           communal standpipe    communal standpipe
9817   30147         0.0  ...           communal standpipe    communal standpipe
6304   60541       100.0  ...                    hand pump             hand pump
13511  51049         0.0  ...                        other                 other
5835   38338         0.0  ...           communal standpipe    communal standpipe
11454  43571         0.0  ...                    hand pump             hand pump
8357     768         0.0  ...           communal standpipe    communal standpipe
5222   44407         0.0  ...                    hand pump             hand pump
4760   51152       500.0  ...           communal standpipe    communal standpipe
6746    6754      5000.0  ...           communal standpipe    communal standpipe
10579  47466        20.0  ...                    hand pump             hand pump
2404   40356         0.0  ...                    hand pump             hand pump
2252   42630         0.0  ...                        other                 other
13344   5243     20000.0  ...  communal standpipe multiple    communal standpipe
1339   12440         0.0  ...           communal standpipe    communal standpipe
13508  39154         0.0  ...  communal standpipe multiple    communal standpipe
13839  23027         0.0  ...           communal standpipe    communal standpipe
634    15036       200.0  ...           communal standpipe    communal standpipe
6590   25763        50.0  ...            

In [30]:
train = train.dropna()
test =test.dropna()

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

train, test = make_classification(n_samples =500, n_features = 4,
                                  n_informative =3, n_redundant =0, random_state =0,
                                  shuffle =False)
classify = RandomForestClassifier(max_depth =2, random_state = 0)
classify.fit(train,test)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [32]:
classify.score(train,test)

0.758

In [33]:
classify.apply(train)

array([[4, 4, 5, ..., 6, 6, 6],
       [4, 4, 5, ..., 6, 6, 6],
       [4, 4, 5, ..., 6, 6, 6],
       ...,
       [4, 4, 6, ..., 6, 6, 6],
       [4, 4, 6, ..., 6, 6, 6],
       [4, 4, 6, ..., 6, 6, 6]])

In [34]:
classify.decision_path(train)

(<500x682 sparse matrix of type '<class 'numpy.longlong'>'
 	with 149848 stored elements in Compressed Sparse Row format>,
 array([  0,   5,  10,  17,  24,  31,  38,  45,  50,  57,  64,  71,  78,
         85,  92,  99, 106, 113, 120, 127, 134, 141, 148, 155, 162, 169,
        176, 183, 190, 197, 204, 211, 218, 225, 232, 239, 246, 253, 260,
        267, 274, 281, 288, 295, 302, 309, 316, 321, 328, 335, 340, 347,
        354, 361, 368, 375, 382, 389, 396, 403, 410, 417, 424, 429, 436,
        443, 448, 455, 462, 469, 476, 483, 488, 495, 502, 509, 516, 523,
        530, 537, 542, 549, 556, 563, 570, 577, 584, 591, 598, 605, 612,
        619, 626, 633, 640, 647, 654, 661, 668, 675, 682]))

In [35]:
classify.predict(train)

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [36]:
classify.predict_log_proba(train)

array([[-0.72047976, -0.66654184],
       [-0.69498873, -0.69130902],
       [-0.78934075, -0.60540024],
       [-0.79794496, -0.59829765],
       [-0.75922697, -0.63116459],
       [-0.67962719, -0.70685247],
       [-0.81180298, -0.587089  ],
       [-0.74986459, -0.6394747 ],
       [-0.74556278, -0.64334268],
       [-0.68154608, -0.70488444],
       [-0.8068438 , -0.59106786],
       [-0.75109309, -0.63837588],
       [-0.85638028, -0.5528577 ],
       [-0.76456286, -0.6264935 ],
       [-0.81154079, -0.58729847],
       [-0.72513484, -0.66215109],
       [-0.81806606, -0.58211443],
       [-0.80220127, -0.5948251 ],
       [-0.79794496, -0.59829765],
       [-0.74556278, -0.64334268],
       [-0.68071892, -0.70573185],
       [-0.74524061, -0.64363364],
       [-0.63612764, -0.75361559],
       [-0.84902308, -0.55832382],
       [-0.9026976 , -0.51999146],
       [-0.80094979, -0.59584335],
       [-0.79794496, -0.59829765],
       [-0.74556278, -0.64334268],
       [-0.81180298,

In [37]:
classify.predict_proba(train)

array([[0.48651879, 0.51348121],
       [0.49908008, 0.50091992],
       [0.45414409, 0.54585591],
       [0.4502533 , 0.5497467 ],
       [0.46802809, 0.53197191],
       [0.5068059 , 0.4931941 ],
       [0.44405672, 0.55594328],
       [0.47243052, 0.52756948],
       [0.4744672 , 0.5255328 ],
       [0.50583433, 0.49416567],
       [0.44626434, 0.55373566],
       [0.47185049, 0.52814951],
       [0.42469659, 0.57530341],
       [0.46553739, 0.53446261],
       [0.44417316, 0.55582684],
       [0.48425927, 0.51574073],
       [0.44128425, 0.55871575],
       [0.44834096, 0.55165904],
       [0.4502533 , 0.5497467 ],
       [0.4744672 , 0.5255328 ],
       [0.50625291, 0.49374709],
       [0.47462009, 0.52537991],
       [0.52933825, 0.47066175],
       [0.42783269, 0.57216731],
       [0.40547438, 0.59452562],
       [0.4489024 , 0.5510976 ],
       [0.4502533 , 0.5497467 ],
       [0.4744672 , 0.5255328 ],
       [0.44405672, 0.55594328],
       [0.47462009, 0.52537991],
       [0.

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform
logistic = LogisticRegression(solver ='saga', tol = 1e-2, max_iter =200,
                              random_state = 0)

distributions = dict(C=uniform(loc =0, scale =4),
                     penalty =['l2','l1'])

clasSearch = RandomizedSearchCV(logistic,distributions, random_state =0)
serch = clasSearch.fit(train, test)

serch.best_params_




{'C': 2.4942547871438894, 'penalty': 'l2'}

In [43]:
serch.decision_function(train)

array([-1.84807131e-01, -5.72758616e-01, -8.14758774e-01, -3.93010254e-01,
       -5.13514215e-01, -8.36245966e-01, -7.22554839e-01, -7.53918485e-02,
       -1.29200465e+00, -1.35934231e+00, -8.45963781e-01, -1.18647996e+00,
       -3.09855320e-01, -6.83905499e-01, -5.23302563e-01, -3.40056630e-01,
       -5.90072008e-01, -8.41793672e-01,  2.00099029e-01, -1.10440220e+00,
       -7.15560117e-01,  5.66042000e-02, -4.13978998e-01, -9.35422064e-02,
       -8.84237567e-01, -1.25211518e+00,  3.18126115e-01, -5.46983900e-01,
       -3.23084159e-01, -1.15827846e+00, -2.33434066e-01, -1.29575168e-01,
       -1.10999069e+00, -9.14444242e-01, -6.37478425e-02, -5.28970932e-01,
        3.37843832e-01, -4.07575342e-01, -1.40700054e+00, -2.23564951e-01,
       -3.73625276e-01, -6.51407680e-01, -3.87740317e-01,  4.44944277e-01,
        4.66572569e-01, -9.99207810e-01, -5.78356836e-01, -4.38833734e-01,
       -4.43400103e-01, -8.77509053e-01, -4.68807196e-01, -1.30945891e-01,
       -3.93929118e-01, -

In [44]:
serch.fit(train,test)

RandomizedSearchCV(cv=None, error_score=nan,
                   estimator=LogisticRegression(C=1.0, class_weight=None,
                                                dual=False, fit_intercept=True,
                                                intercept_scaling=1,
                                                l1_ratio=None, max_iter=200,
                                                multi_class='auto', n_jobs=None,
                                                penalty='l2', random_state=0,
                                                solver='saga', tol=0.01,
                                                verbose=0, warm_start=False),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fc132c43c88>,
                                        'penalty': ['l2', 'l1']},
                   pre_dispatch='2*n_jobs', random_state=0, refit=True,
                   return_tra

In [47]:
serch.predict(train)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [49]:
serch.predict_log_proba(train)

array([[-6.05006763e-01, -7.89813894e-01],
       [-4.47225875e-01, -1.01998449e+00],
       [-3.66548323e-01, -1.18130710e+00],
       [-5.15826195e-01, -9.08836450e-01],
       [-4.68996254e-01, -9.82510470e-01],
       [-3.60003356e-01, -1.19624932e+00],
       [-3.95758329e-01, -1.11831317e+00],
       [-6.56161579e-01, -7.31553428e-01],
       [-2.42726166e-01, -1.53473082e+00],
       [-2.28592389e-01, -1.58793470e+00],
       [-3.57075355e-01, -1.20303914e+00],
       [-2.66428319e-01, -1.45290828e+00],
       [-5.50173105e-01, -8.60028425e-01],
       [-4.08555168e-01, -1.09246067e+00],
       [-4.65343001e-01, -9.88645564e-01],
       [-5.37504564e-01, -8.77561195e-01],
       [-4.41017158e-01, -1.03108917e+00],
       [-3.58329384e-01, -1.20012306e+00],
       [-7.98193320e-01, -5.98094291e-01],
       [-2.86237734e-01, -1.39063994e+00],
       [-3.98049805e-01, -1.11360992e+00],
       [-7.21849732e-01, -6.65245532e-01],
       [-5.07428761e-01, -9.21407759e-01],
       [-6.

In [50]:
serch.score(train,test)

0.828

Cross-Validation Attempt with OrdinalEncoder

In [56]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OrdinalEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer


cate_form = make_pipeline(OrdinalEncoder(),
                                      SimpleImputer(),
                                      StandardScaler(),
                                      LogisticRegression(multi_class ='auto', solver='lbfgs',
                                                          n_jobs=-1))
cate_form.fit(train,test)
score = cate_form.score(train,test)



In [57]:
print('Logistic Regression, Validation Accuracy', score)

Logistic Regression, Validation Accuracy 0.758


In [73]:
clasfier = make_pipeline(OrdinalEncoder(),
                         SimpleImputer(),
                         RandomForestClassifier(n_estimators =100, criterion ='gini',max_depth=2, random_state =42))
clasfier.fit(train,test)
scored = clasfier.score(train,test)

print('Random Forest Classifier Validation Accuracy Score',scored)


Random Forest Classifier Validation Accuracy Score 0.77


In [74]:
from sklearn.model_selection import cross_val_score

pipeline = make_pipeline(OrdinalEncoder(),
                         SimpleImputer(),
                         StandardScaler(),
                                        RandomForestClassifier())
k =3
cscore = cross_val_score(pipeline,train,test, cv =k,
                         scoring ='neg_mean_absolute_error')
print(f'MAE for {k} folds:' , -cscore)

ValueError: ignored

In [75]:
-cscore.mean()

NameError: ignored